name: alaska-verify
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - pandas
  - numpy
  - xarray
  - fsspec
  - s3fs
  - pyarrow
  - eccodes
  - cfgrib
  - requests
  - python-dateutil
  - pip
  - pip:
      - shutil  # Note: shutil is a standard library; pip installs will ignore this